[package]
name = "cw-skeleton-pkg"
version = "0.1.0"
authors = ["Mike Purvis @mikedotexe"]
edition = "2021"
repository = "https://github.com/mikedotexe/cw-skeleton"
license = "MIT OR Apache-2.0"
description = "Helper package for cw-skeleton CosmWasm smart contract"

[dependencies]
cosmwasm-std = "1.2.5"
cosmwasm-schema = "1.2.5"
thiserror = "1.0.40"
cw-storage-plus = "1.0.1"

# Make sure you've run: "cargo install cargo-run-script"
# Then you can run the scripts below, like: "cargo run-script optimize"
[package.metadata.scripts]
unit-test = "cargo +nightly test --lib"
# This is a fast way to run "cargo check" ignoring (most) warnings
check-no-warnings = """RUSTFLAGS="-A warnings" cargo check"""
test-no-warnings = """RUSTFLAGS="-A warnings" cargo test -- --nocapture"""
